### PR TITLE
Some fix

### PR DESCRIPTION
**Pull request by supdrewin**
The following are the changes for this PR:

- Some typo fix (AUR install files)
- Systemd service dependency fix (*.device)
- opencv flags fix

_Sorry but I'm trying to install the unreleased 4.0.0._

### CODE REVIEW

**Comment by EmixamPP** [comment]
Is the emitter works for you after sleep state ? 
For some strange reason, at home not, systemd can't access the camera. And even when I want to start it manually with systemctl start linux-enable-ir-emitter.

**Comment by EmixamPP** [comment]
> Is the emitter works for you after sleep state ? For some strange reason, for me it didn't, systemd can't access the camera. And even when I want to start it manually with `systemctl start linux-enable-ir-emitter`.

Was a SELinux issue; fixed in a099013d0a04ab2a3769277238be0714650f3295

**Comment by EmixamPP** [comment]
And for all distro in c26df40f5d6e0e9c87bf28ef6f688edfe690d5d1

**Comment by supdrewin** [comment]
Sorry for the delay. SELinux doesn't installed in my system but I'm sure the emitter work fine after wake up from sleep. Thanks for your work!

**Pull request merged**
