### PR TITLE
fix imports dependencies

### PR DESCRIPTION
**Pull request by Diaoul**
This allows for the tool not to depend on opencv and pyshark for normal operations.

### CODE REVIEW

**Comment by EmixamPP** [comment]
For simplicity's sake, I have now decided not to "allow" the software to be used without installing it. I also tried to improve the installation of the dependencies via the bash script. And I explained in the readme how to install the package without going through AUR which is not up to date.

**Comment by Diaoul** [comment]
Those changes are made to avoid the need to have opencv installed on the system when no command using opencv will be used. Same for pyshark.

python-pyshark:
```Total Installed Size:  111.62 MiB```
python-opencv
```Total Installed Size: 202.77 MiB```

In #24 I made those optional dependencies which is a common thing to do in those cases, but currently even basic command will crash on import error as those imports are made first and not on the command depending on it.

**Comment by EmixamPP** [comment]
Oh right, the two PR are linked, I understand better. 
However, without opencv, no command can work (unless it was uninstalled after the quick configuration) and in general, opencv is already installed (Howdy uses it). But ok, why not for pyshark it makes it possible to save some MB. Even though nowadays 100Mib is not much.

I will push in another commit with the changes for pyshark and an update for the package. 

Merci beaucoup d'avoir pris le temps de me partager ton expérience :smile:.

**Comment by Diaoul** [comment]
That is true, I use howdy so opencv is installed anyways. I think python-opencv isn't even listed as dependency to howdy even though it is required...
The main concern about having dependencies is not only the space but the headache of solving an issue if any arise. pyshark pulls wireshark from dependencies in the AUR and that comes with many others that I don't want to deal with :)

De rien :wink:

**Pull request closed without merging**
